# render.yaml
services:
  - type: web
    name: realtime-visitor-counter
    env: docker
    region: oregon
    plan: free
    autoDeploy: true
    dockerCommand: ""
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3000